### ISSUE TITLE
Wiedergabe geht nicht

### ISSUE THREAD

**Issue by illulix** [xaverW/MTPlayer#14]
Seit dem Update auf Version 13 geht die Wiedergabe nicht mehr. Im Terminal erscheint zwar der korrekte Aufruf,
aber es startet keine Wiedergabe. (Siehe Logfile)
Wenn ich die Zeile kopiere und dann ins Terminal kopieren geht es.

[P2Tools_0.log](https://github.com/xaverW/MTPlayer/files/11081922/P2Tools_0.log)

**Comment by xaverW** [comment]
Hi,

[20:05:43] SCHWERWIEGEND: 450028932  Fehler beim Starten
          java.io.IOException: Cannot run program "/usr/bin/mpv": error=13, Keine Berechtigung

das ist die Fehlermeldung aus dem Log, da stimmt vielleicht was mit den Berechtigungen nicht??

**Comment by LinuxOpa** [comment]
im Terminal:
1. which mpv - liegt mpv in /usr/bin ?
2. sudo chmod u+x /usr/bin/mpv
    u stands for user.
    g stands for group.
    o stands for others.
    a stands for all.
    x stands for execute

**Comment by illulix** [comment]
Hi,
Erstmal Danke für Eure Hilfe :)

stat /usr/bin/mpv
  File: /usr/bin/mpv
  Size: 3180744         Blocks: 6224       IO Block: 4096   regular file
Device: 259,2   Inode: 3414390     Links: 1
Access: (0755/-rwxr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2023-03-19 00:41:34.000000000 +0100
Modify: 2023-03-19 00:41:34.000000000 +0100
Change: 2023-03-20 14:49:49.392785129 +0100
 Birth: 2023-03-20 14:49:49.376785416 +0100

burdon: # ls -l /usr/bin/mpv
-rwxr-xr-x 1 root root 3180744 Mar 19 00:41 /usr/bin/mpv

**Die Lösung in Kurzfassung: Es liegt an dem mitgelieferten JAVA.**

Die Langfassung:

Wie gesagt, ich kann mpv ja von der shell starten.
----8<----
bernd@burdon:~> mpv  https://apasfiis.sf.apa.at/ipad/cms-worldwide_episodes/14172742_0009_Q8C.mp4/playlist.m3u8
 (+) Video --vid=1 (h264 1280x720 25.000fps) (3604 kbps)
 (+) Audio --aid=1 (aac 2ch 48000Hz) (3604 kbps)
AO: [pulse] 48000Hz stereo 2ch float
VO: [gpu] 1280x720 yuv420p
AV: 00:03:09 / 00:40:35 (8%) A-V:  0.000 Cache: 357s/150MB
[ffmpeg/demuxer] hls: maybe the m3u8 list sequence have been wraped.
[...]
----8<----

Mit mtplayer 12 geht's ja auch noch, der hat aber leider Probleme beim Download einer neuen Filmliste.

Hab mal eben firefox als Hilfsprogramm eingetragen.
Das Ergebnis:
----8<----
  =====================
[11:01:30] INFORMATION:  Starte Array: 
[11:01:30] INFORMATION:   -> /usr/bin/firefox<>https://hrardmediathek-a.akamaihd.net/video/as/allgemein/2023_03/hrLogo_230327095805_0200589_A01_960x540-50p-1600kbit.mp4
[11:01:30] INFORMATION:  =====================
[11:01:30] SCHWERWIEGEND: 450028932  Fehler beim Starten
          java.io.IOException: Cannot run program "/usr/bin/firefox": error=13, Keine Berechtigung
                at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
                at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
                at java.base/java.lang.Runtime.exec(Runtime.java:615)
                at java.base/java.lang.Runtime.exec(Runtime.java:474)
                at de.p2tools.mtplayer.controller.starter.RuntimeExec.exec(RuntimeExec.java:87)
                at de.p2tools.mtplayer.controller.starter.ExternalProgramDownload.startDownload(ExternalProgramDownload.java:157)
                at de.p2tools.mtplayer.controller.starter.ExternalProgramDownload.downloadLoop(ExternalProgramDownload.java:115)
                at de.p2tools.mtplayer.controller.starter.ExternalProgramDownload.run(ExternalProgramDownload.java:96)
          Caused by: java.io.IOException: error=13, Keine Berechtigung
                at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
                at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:319)
                at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:249)
                at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
                ... 7 more


[11:01:30] INFORMATION:  ------------------------------------------------------------
                         Film fertig
                         Startzeit: 11:01:30
                         Endzeit: 11:01:30
                         Dauer: 0 s
                         URL: https://hrardmediathek-a.akamaihd.net/video/as/allgemein/2023_03/hrLogo_230327095805_0200589_A01_960x540-50p-1600kbit.mp4
                         Programmaufruf: /usr/bin/firefox https://hrardmediathek-a.akamaihd.net/video/as/allgemein/2023_03/hrLogo_230327095805_0200589_A01_960x540-50p-1600kbit.mp4
                         Programmaufruf[]: /usr/bin/firefox<>https://hrardmediathek-a.akamaihd.net/video/as/allgemein/2023_03/hrLogo_230327095805_0200589_A01_960x540-50p-1600kbit.mp4
-----8<------

Kann  sein, dass es an JAVA liegt.
Da hab ich leider zuwenig Ahnung davon :)

Ich hab jetzt doch mal was versucht:
Als root :/opt/MTPlayer13/Java umbenannt:
burdon:/opt/MTPlayer13 # mv Java Java-Org
Als user
bernd@burdon:/opt/MTPlayer13> ./MTPlayer__Linux+Java.sh
dann Java vom System
[11:12:19] INFORMATION:  Proxy Authentication: not configured
März 28, 2023 11:12:19 AM com.sun.javafx.application.PlatformImpl startup
WARNUNG: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @7deec4e'

(java:5470): dconf-WARNING **: 11:12:20.178: Unable to open /var/lib/flatpak/exports/share/dconf/profile/user: Keine Berechtigung
[11:12:20] INFORMATION:  Anz. Listener: 0
[11:12:20] INFORMATION:  Anz. Listener: 1
[11:12:20] INFORMATION:  Anz. Listener: 2
[...]
[11:12:32] INFORMATION:  =====================================
                         Updatesuche: https://www.p2tools.de/download/
                         erst mal Programmversionen auf build-date dieser laufenden Version heben
                         Aktuelle Version: 2023.03.07
                           old: 2023.03.07  isNewFound: 2023.03.07
                           -> gibt nichts oder schon mal angezeigt
                         Beta-Version: 2023.03.07
                           old: 2023.03.07  isNewFound: 2023.03.07
                           -> gibt nichts oder schon mal angezeigt
                         Daily: 2023.03.26
                           old: 2023.03.26  isNewFound: 2023.03.07
                           -> gibt nichts oder schon mal angezeigt
[11:12:32] INFORMATION:  Downloads aus Abos suchen
[11:12:33] INFORMATION:  TipOfDay: Heute schon gemacht oder keine neuen Tips
[11:12:33] INFORMATION:  ========================================
[11:12:33] INFORMATION:           === Filter: 1 ===
[11:12:33] INFORMATION:  ========================================
[11:12:36] INFORMATION:  An Historyliste anfügen: 1, Datei: history.txt
[11:12:36] INFORMATION:  ------------------------------------------------------------
                         Film abspielen
                         URL: https://rodlzdf-a.akamaihd.net/none/3sat/23/03/230326_danziger_kabarett/1/230326_danziger_kabarett_2360k_p35v17.mp4
                         Startzeit: 11:12:36
                         Programmaufruf: /usr/bin/mpv https://rodlzdf-a.akamaihd.net/none/3sat/23/03/230326_danziger_kabarett/1/230326_danziger_kabarett_2360k_p35v17.mp4
                         Programmaufruf[]: /usr/bin/mpv<>https://rodlzdf-a.akamaihd.net/none/3sat/23/03/230326_danziger_kabarett/1/230326_danziger_kabarett_2360k_p35v17.mp4
                           
[11:12:36] INFORMATION:  =====================
[11:12:36] INFORMATION:  Starte Array: 
[11:12:36] INFORMATION:   -> /usr/bin/mpv<>https://rodlzdf-a.akamaihd.net/none/3sat/23/03/230326_danziger_kabarett/1/230326_danziger_kabarett_2360k_p35v17.mp4
[11:12:36] INFORMATION:  =====================
[11:12:37] EXT_TOOL:     [00001] >> INPUTSTREAM:  (+) Video --vid=1 (*) (h264 1024x576 25.000fps)
[11:12:37] EXT_TOOL:     [00001] >> INPUTSTREAM:  (+) Audio --aid=1 --alang=deu (*) (aac 2ch 48000Hz)
[11:12:37] EXT_TOOL:     [00001] >> INPUTSTREAM: AO: [pulse] 48000Hz stereo 2ch float
[11:12:37] EXT_TOOL:     [00001] >> INPUTSTREAM: VO: [gpu] 1024x576 yuv420p
[11:12:38] EXT_TOOL:     [00001] >> ERRORSTREAM: 
[11:12:38] EXT_TOOL:     [00001] >> ERRORSTREAM: AV: 00:00:00 / 00:44:09 (0%) A-V:  0.000 Cache: 5.3s/1MB
[11:12:38] EXT_TOOL:     [00001] >> ERRORSTREAM: 
[11:12:38] EXT_TOOL:     [00001] >> ERRORSTREAM: AV: 00:00:00 / 00:44:09 (0%) A-




Ein paar Infos zum OS:
Betriebssystem: openSUSE Tumbleweed 20230318
KDE-Plasma-Version: 5.27.3
KDE-Frameworks-Version: 5.104.0
Qt-Version: 5.15.8
Kernel-Version: 6.2.6-3.g25f0428-default (64-bit)
Grafik-Plattform: X11
Prozessoren: 16 × AMD Ryzen 7 1700 Eight-Core Processor
Speicher: 15,5 GiB Arbeitsspeicher
Grafikprozessor: VERDE
java -version
openjdk version "1.8.0_362"
OpenJDK Runtime Environment (IcedTea 3.26.0) (build 1.8.0_362-b09 suse-1.1-x86_64)
OpenJDK 64-Bit Server VM (build 25.362-b09, mixed mode)

**Comment by LinuxOpa** [comment]
Von der Seite: [https://www.p2tools.de/mtplayer/download.html](https://www.p2tools.de/mtplayer/download.html) :

"Unterstützt wird Windows und Linux. Das Programm benötigt eine aktuelle Java-VM ab Version: Java 11. Für Linux-Benutzer wird OpenJDK11 empfohlen. (FX-Runtime bringt das Programm bereits mit und muss nicht installiert werden)."

    Java 8 is now 1.8.0_362 passt wohl nicht 
    Java 11 is now 11.0.18 sollte es wohl mindestens sein
    Java 13 is now 13.0.14
    Java 15 is now 15.0.10
    Java 17 is now 17.0.6
    Java 19 is now 19.0.2

**Comment by illulix** [comment]
Hi,
installiert ist ja von dort:
<https://www.p2tools.de/download/mtplayer/act/MTPlayer-13__Linux+Java__2023.03.07.zip>
Und mit der Java Umgebung die da dabei ist, tritt der Fehler auf.

Apropos Linux Opa... Ich dachte immer, das bin ich :)) SCNR

**Comment by xaverW** [comment]
das programm verwendet die mitgelieferte Java-Version,
aus dem log:

  
                         #  Java
                         #  Vendor:  Oracle Corporation
                         #  VM-Name: OpenJDK 64-Bit Server VM
                         #  Version: 19.0.1
                         #           Feature: 19  Interim: 0  Update: 1  Patch: 0
                         #           Runtimeversion: 19.0.1+10-21


das Problem ist, dass das Programm mit einem Benutzer läuft, der deine Programme:

  * Cannot run program "/usr/bin/mpv": error=13, Keine Berechtigung

starten darf oder das Programm liegt wo ganz anders.

Versuchs doch mal one Pfadangabe, nur "mpv"

**Comment by vitusson** [comment]
> das Problem ist, dass das Programm mit einem Benutzer läuft, der deine Programme:
> 
>     * Cannot run program "/usr/bin/mpv": error=13, Keine Berechtigung
> 
> 
> starten darf oder das Programm liegt wo ganz anders.

Problem liegt bei dieser Flatpak Seuche
>(java:5470): dconf-WARNING **: 11:12:20.178: Unable to open /var/lib/flatpak/exports/share/dconf/profile/user: Keine Berechtigung

**Comment by LinuxOpa** [comment]
> Hi, installiert ist ja von dort: https://www.p2tools.de/download/mtplayer/act/MTPlayer-13__Linux+Java__2023.03.07.zip Und mit der Java Umgebung die da dabei ist, tritt der Fehler auf.

probier die mal:
[https://www.p2tools.de/download/mtplayer/daily/MTPlayer-13-48__2023.03.26.zip](https://www.p2tools.de/download/mtplayer/daily/MTPlayer-13-48__2023.03.26.zip)

rennt in ubuntu 20.04.06 LTS wie die Zau!

> 
> Apropos Linux Opa... Ich dachte immer, das bin ich :)) SCNR

nixda - det bin ick!

**Comment by illulix** [comment]
Hi,
installiert ist ja von dort:
<https://www.p2tools.de/download/mtplayer/act/MTPlayer-13__Linux+Java__2023.03.07.zip>
Und mit der Java Umgebung die da dabei ist, tritt der Fehler auf.

Apropos Linux Opa... Ich dachte immer, das bin ich :)) SCNR

**Comment by LinuxOpa** [comment]
achte auf die Version 03.07<>03.26!

**Comment by xaverW** [comment]
> Hi, installiert ist ja von dort: https://www.p2tools.de/download/mtplayer/act/MTPlayer-13__Linux+Java__2023.03.07.zip Und mit der Java Umgebung die da dabei ist, tritt der Fehler auf.
> 
> Apropos Linux Opa... Ich dachte immer, das bin ich :)) SCNR

Das liegt aber nicht an Java/JRE, das ist ein Problem der Berechtigung.
Wenn das mitgelieferte JRE verwendet wird, läuft es mit den Rechten des Users, der das Programm startet. Wenn du die System-JRE verwendes (das Paket das kein JRE dabei hat), dann läuft das SystemJRE möglicherweise mit anderen Rechten!!

Das macht den Unterschied aus, das Paket mit mitgelieferten JRE läuft unter Linux sonst problemlos.

**Comment by illulix** [comment]
Ok,
ich sehe, hier sitzt der Fehler wieder vor der Tastatur :))
Ich hatte das ZIP File via Midnight Commander entpackt. (Doppelklick)
Dabei werden offenbar die Rechte nicht korrekt gesetzt.
Eben hab ich das mit unzip entpackt. Da stimmen die Rechte...
Wieder was gelernt :)))
Also sorry für die Aufregung :)
Und vielen Dank für das schöne Progamm!
